# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and test
        run: |
          python -m pip install --upgrade pip
          pip install -r quantumkey-api/requirements.txt

          # Перейти в папку API и добавить её в PYTHONPATH
          cd quantumkey-api
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

          # Запустить pytest через python -m
          python -m pytest --maxfail=1 --disable-warnings -q

  frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & build
        run: |
          cd quantumkey-frontend
          npm ci
          npm run build
