# .github/workflows/ci.yml

jobs:
  Backend Tests:
    runs-on: ubuntu-latest

    # <— Вот это добавляем:
    defaults:
      run:
        working-directory: ./quantumkey-api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
