name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend:
    name: 🐍 Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        working-directory: ./quantumkey-api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        working-directory: ./quantumkey-api
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q

  frontend:
    name: ⚛️ Frontend Build
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./quantumkey-frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./quantumkey-frontend
        run: npm run build
